language: node_js
node_js:
  - "8"
  
cache:
  directories:
    - node_modules
  
before_script:
  - yarn add -g babel-cli
  
script: 
  - yarn run lint
  - yarn run build

branches:
  only:
  - master